//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanSpots.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string User { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public int BusinessId { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
